from .controller_authentication import AuthenticationController
from .controller_document_management import DocumentManagementController
from .controller_document_details import DocumentDetailsController
from .controller_search import SearchController
from .controller_home import HomeController
from .controller_user_profile import UserProfileController